### ISSUE TITLE
VWATCH has compile errors

### ISSUE THREAD

**Issue by MRLambert** [FellippeHeitor/vWATCH64#1]
$IF $ENDIF $END _Commandcount ... brings up errors
$IF WIN THEN
    DECLARE LIBRARY
        FUNCTION PlaySound (pszSound AS STRING, BYVAL hmod AS INTEGER, BYVAL fdwSound AS INTEGER)
    END DECLARE
    DECLARE DYNAMIC LIBRARY "kernel32"
        FUNCTION OpenProcess& (BYVAL dwDesiredAccess AS LONG, BYVAL bInheritHandle AS LONG, BYVAL dwProcessId AS LONG)
        FUNCTION CloseHandle& (BYVAL hObject AS LONG)
        FUNCTION GetExitCodeProcess& (BYVAL hProcess AS LONG, lpExitCode AS LONG)
    END DECLARE
$ELSE
    DECLARE LIBRARY
    FUNCTION PROCESS_CLOSED& ALIAS kill (BYVAL pid AS INTEGER, BYVAL signal AS INTEGER)
    END DECLARE
$END IF
IF LEN(COMMAND$) THEN
    IF _COMMANDCOUNT > 1 THEN
        'Set flags based on command line arguments:
        FOR i = 1 TO _COMMANDCOUNT
 SELECT CASE LCASE$(COMMAND$(i))  *****\* also brings up an error

**Comment by FellippeHeitor** [comment]
~~I'll check it out and get back to you. Could you send your full .bas source which is triggering the issue, so I can fully test it?~~ Only now I noticed this code belongs to vWATCH64 itself, not to some of your programs which you tried to process with vWATCH. IF you can't compile vWATCH, you're probably not using one of the latest daily builds of QB64, which is a requirement. Please download one of the latest daily builds from www.qb64.net and try again.

**Comment by MRLambert** [comment]
Thank you

**Comment by MRLambert** [comment]
Hi Fellippe,

 

VWatch is a great tool .. thank you.

 

I use it extensively to debug my QB64 programs. 

I find that if I have source code made up of continuation lines, then vWatch64 will not compile the program.

 

e.g.

 

Line Input #1, Fld1_

                          FLD2_

                          FLD3

 

The actual example is

 

                                   Field 6, 88 as TMKey$_

                                          , 80 as TMTeam$_

                                          , 8  as TMDate$_

                                          , 40 as TMSur1$_

                                          , 40 as TMFir1$_

                                          , 2  as TMPosn1$_

                                          , 40 as TMSur2$_

                                          , 40 as TMFir2$_

                                          , 2  as TMPosn2$_

                                          , 40 as TMSur3$_

                                          , 40 as TMFir3$_

                                          , 2  as TMPosn3$_

                                          , 40 as TMSur4$_

                                          , 40 as TMFir4$_

                                          , 2  as TMPosn4$_

                                          , 40 as TMSur5$_

                                          , 40 as TMFir5$_

                                          , 2  as TMPosn5$_

                                          , 40 as TMSur6$_

                                          , 40 as TMFir6$_

                                          , 2  as TMPosn6$_

                                          , 40 as TMSur7$_

                                          , 40 as TMFir7$_

                                          , 2  as TMPosn7$_

                                          , 40 as TMSur8$_

                                          , 40 as TMFir8$_

                                          , 2  as TMPosn8$_

                                          , 40 as TMSur9$_

                                          , 40 as TMFir9$_

                                          , 2  as TMPosn9$_

                                          , 40 as TMSur10$_

                                          , 40 as TMFir10$_

                                          , 2  as TMPosn10$_

                                          , 40 as TMSur11$_

                                          , 40 as TMFir11$_

                                          , 2  as TMPosn11$_

                                          , 40 as TMSur12$_

                                          , 40 as TMFir12$_

                                          , 2  as TMPosn12$_

                                          , 40 as TMSur13$_

                                          , 40 as TMFir13$_

                                          , 2  as TMPosn13$_

                                          , 40 as TMSur14$_

                                          , 40 as TMFir14$_

                                          , 2  as TMPosn14$_

                                          , 40 as TMSur15$_

                                          , 40 as TMFir15$_

                                          , 2  as TMPosn15$_

                                          , 1  as TMStatus$_

                                          , 40 as TMFullDate$_

                                          , 80 as TMVenueName$_

                                          , 3  as TMScore$_

                                          , 10 as TMRound$_

                                          , 80 as TMComp$_

                                          , 1  as TMSNFlag$_

                                          , 50 as TMCoach$_

                                          , 8  as TMCrowdSize$_

                                          , 1  as TMHAFlag$_

                                          , 80 as TMOpTeam$_

                                          , 6  as TMTotChg$_

                                          , 6  as TMTotReln$_

                                          , 6  as TMTotGames$_

                                          , 6  as TM12MthI$_

                                          , 6  as TM24MthI$_

                                          , 6  as TM12MthE$_

                                          , 6  as TM24MthE$_

                                          , 6  as TM5Reln$_

                                          , 6  as TM10Reln$_

                                          , 6  as TM5RelnS$_

                                          , 6  as TM10RelnS$_

                                          , 6  as TMSpare5$_

                                          , 6  as TMTotChgS$_

                                          , 6  as TMTotRelnS$_

                                          , 6  as TMTotGamesS$_

                                          , 6  as TM12MthSI$_

                                          , 6  as TM24MthSI$_

                                          , 6  as TM12MthSE$_

                                          , 6  as TM24MthSE$_

                                          , 6  as TM97$_

                                          , 6  as TM96$_

                                          , 6  as TM91$_

                                          , 6  as TM76$_

                                          , 6  as TM71$_

                                          , 6  as TM61$_

                                          , 6  as TMSpare12$_

                                          , 48 as TMFiller48$

 

I have tried the latest version but the problem still exists.

 

Thks,

 

Mike

**Comment by FellippeHeitor** [comment]
Hello, Mike.

That's one heckuva long FIELD statement line.

Anyway, I pasted that onto an empty program, see it here: 
http://qb64.org/basbin/B9CF.txt

vWATCH did have issues with that line, in that it only detected the first variable, but that didn't prevent it from compiling.

![vwatch](https://user-images.githubusercontent.com/10699359/44564634-5a510100-a73a-11e8-81db-4391d750d8b7.png)

Is it **version 1.104** you have there?

I understand it makes your program more easy to read having the line broken down like that, but maybe it'd be more reasonable in your final, bug-free version. While you're still debugging, one quick solution here would be having it all in a single line perhaps.

I'll consider looking into that for a future update of vWATCH. Thank you so much for your interest and for reporting this.
