### ISSUE TITLE
C++ Compilation Failed

### ISSUE THREAD

**Issue by MRLambert** [FellippeHeitor/vWATCH64#2]
Hi, I downloaded the latest daily QB64 version to fix a compile error in VWatch ...this worked fine ... except now I get C++ Compilation Failed in my .BAS program which used to compile cleanly. 
How do I determine what part of my code is generating this error ?
Just tried Print "Hello" and nothing else ... same problem.
Thks,

Mike

**Comment by FellippeHeitor** [comment]
Did you unpack all the contents of the zip you download to a new folder or did you just extract qb64.exe?

**Comment by MRLambert** [comment]
Hi, 

Thank you for the quick response. 

I unpacked the complete package.

Mike

**Comment by MRLambert** [comment]
Hi, 
I downloaded version 06 06 2016, unzipped full package again ... this time no C++ Compilation Failed error message. I compared directories from yesterday's download against today's download .. exactly the same .. including sizes.
Gremlins..

Thks for your help .

Mike

**Comment by FellippeHeitor** [comment]
You're most welcome!
