### ISSUE TITLE
Step over

### ISSUE THREAD

**Issue by ep12** [FellippeHeitor/vWATCH64#3]
It'd be helpful to be able to stay on the same call level while stepping into subs and functions. My call stack is huge sometimes and it takes long when stepping into subs/functions every time...

**Comment by FellippeHeitor** [comment]
Try Shift+F8, is that what you are looking for?

**Comment by ep12** [comment]
Yeah, thank you! 😄  Honestly, why is this feature hidden? If you've been hiding more features, a md help file would be helpful! By the way: Thank you for maintaining the best debugger for qb64! Don't hide features from the users 😄

**Comment by FellippeHeitor** [comment]
Thanks for the kind words!

I went the wiki route for InForm, I must do the same for vWATCH soon. ;-)
