### ISSUE TITLE
Quick Watch and/or Selected Variables do not show any values as program processes

### ISSUE THREAD

**Issue by MRLBEL** [FellippeHeitor/vWATCH64#4]
I have tried quick watch and selecting a few variables in my program but when the program runs using F8 or F5 the variables remain blank or zero ... they do not change or update

**Comment by FellippeHeitor** [comment]
Quick Watch variables - those added automatically to the bottom of the source view as you step through with F8, are indeed supposed to disappear while execution with F5 is requested. 

However, if you pin any variables (clicking them in Variable View) they should properly update in the Source View while your program is running, even with F5.

I can have a look if vWATCH64 is interacting incorrectly with your code specifically if you're willing to share it. You can either paste it at qb64.org/basbin and send me the link or send your files to me privately to the address fellippe *a*t* qb64 dot org

**Comment by MRLBEL** [comment]
Hi Fellippe,

 

Thank you for your time and quick response. I will send a program to you.

 

I apologise for contacting you directly but I have tried many many time to register on the QB64.net forum for vWatch64 but all attempts have been unsuccessful.

 

Regards,

 

Mike

**Comment by FellippeHeitor** [comment]
No problem at all contacting me directly. I appreciate the bug reports, keep them coming.

I will wait for your code so I can run tests and then get back to you on the issue.

Concerning the forums, a quick tip is to observe the "I'm not a bot" address you must manually type. Find it in the page with instructions for registering. If that doesn't cut it, try using an alternative email address (guerilla mail, maybe) to register, then edit it in your profile page once registration succeeds.

**Comment by FellippeHeitor** [comment]
@MRLBEL Are you still having issues?

**Comment by MRLambert** [comment]
Hi Fellippe,

 

The issue I originally spoke about … yes it still exists. The program is so big and complicated that I could not send it to you. 

I have a work around so no problem anymore.

I apologise for not responding to you earlier. 

Thank you very much.

 

Regards,

 

Mike

**Comment by FellippeHeitor** [comment]
Ler me know if you need any extra assistance with vWATCH64.
