### ISSUE TITLE
New features for single stepping

### ISSUE THREAD

**Issue by ghost** [FellippeHeitor/vWATCH64#6]
Hi Fellippe,
after using your great tool for some time now to debug my programs, I'd like to suggest you to add two more single stepping commands/hotkeys, which you find in many other debugging tools.

Although we've the chance to "Set Next Line" and "Break-/Watchpoints" and also can exclude some code with 'VWATCH64:OFF/ON (the latter I use mainly to exclude error free and working SUBs and FUNCTIONs), it would also be nice to have hotkeys for STEP THROUGH and SKIP TO NEXT (just like the F8 - SINGLE STEP),  hence you don't need to set Breakpoints or Set Next Line or even adding 'VWATCH64:OFF and recompile, just to go through a subroutine quickly (if you know it works bugfree) or if you just wanna skip a line of code or two or three.

STEP THROUGH
If the the next instruction to execute is a SUB/FUNCTION or GOSUB call, then just execute the entire call at once without (in difference to F8) single stepping into the subroutine code, but rather directly continue single stepping with the instruction following the SUB call.
If the instruction is no SUB/FUNCTION/GOSUB call but a regular instruction, then this command should just behave like a regular F8 - SINGLE STEP of course.

SKIP TO NEXT
Very easy, just skip to the next instruction without executing the current one.

So, with these implemented into vWatch64, we could quick and easy (sequencially) single stepping through our entire program and also fast skipping "known to be working" subroutine code with just three hotkeys. No need to extesively using Breakpoints, Next Lines or even commenting with 'VWATCH64:OFF/ON.

Kind regards
Roland

**Comment by ghost** [comment]
Well, sorry Fellippe,
should have updated to the latest version first, before doing this feature request. I see there are already the STEP OVER and SKIP THIS LINE entries in the context menu now. But however, even choosing these commands from the context menu for every single  SUB/FUNCTION/GOSUB call seems a little bulky for me, so nevertheless some hotkey defines would be much appreciated here.
Thanx

**Comment by FellippeHeitor** [comment]
Hi there, man!

Well, for STEP THROUGH, try holding Shift when a line with a SUB/FUNCTION call (no GOSUB yet) is next to be executed and you'll see the Step button turn into (just differently named) **Step Over**. It's there, just not well documented as you can see.

About skipping a line, you can currently set lines to be skipped by Right Click->Skip this line, which will color the marked line yellow and bypass it next time it's reached. I understand your request is slightly different, right?

**Comment by FellippeHeitor** [comment]
Oops, you replied while I was typing, so in summary: Shift+F8 to step over/through and Skip This Line from the context menu.
