### ISSUE TITLE
Allow searching for code

### ISSUE THREAD

**Issue by MRLBEL** [FellippeHeitor/vWATCH64#9]
Hi,
It would be handy to be able to search for particular code within the source code view. I have some big programs that I need to debug using vWATCH64 and to find code I have to scroll thru' numerous pages over and over.
Thks..

**Comment by FellippeHeitor** [comment]
Just start typing 😉

Once you find the line you want, you can filter by line range. Hit tab and enter a line number or a line range like 10-50 or even single lines to display like 10-50;55 or even multiple ranges like 1-40;100-200.
